name: Python Linter
on: [push, pull_request]

jobs:
  lint:
    name: Run python linter on wsadmin code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: false
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install linter
        run: pip install pylint
      - name: Run linter
        run: pylint . --recursive=y
