name: Python Linter
on: [push, pull_request]

jobs:
  lint:
    name: Run python linter on wsadmin code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: false
      - name: Run linter
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
      - name: Run typechecker
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pytype
